// Code generated by goctl. DO NOT EDIT.
package types

type LoginReply struct {
	Token string `json:"token"`
}

type LoginRequest struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

type Request struct {
	Name string `path:"name,options=you|me"`
}

type Response struct {
	Message string `json:"message"`
}

type SendCodeReply struct {
	Message string `json:"message"`
}

type SendCodeRequest struct {
	Email string `json:"email"`
}

type UserDeatilReply struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

type UserDeatilRequest struct {
	Identity string `json:"identity"`
}

type UserRegisterReply struct {
	Message string `json:"message"`
}

type UserRegisterRequest struct {
	Name     string `json:"name"`
	Password string `json:"password"`
	Email    string `json:"email"`
	Code     string `json:"code"`
}
